# Generated by Django 3.2.4 on 2021-08-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='publish',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('django', 'Django'), ('sql', 'SQL'), ('whitenoise', 'Whitenoise'), ('javascript', 'JavaScript'), ('bootstrap5', 'Bootstrap5')], default='No Topic', max_length=254),
        ),
    ]
