# Generated by Django 3.2.4 on 2021-08-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210801_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='excerpt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('django', 'Django'), ('stripe', 'Stripe'), ('sql', 'SQL'), ('whitenoise', 'Whitenoise'), ('bootstrap5', 'Bootstrap5'), ('javascript', 'JavaScript')], default='No Topic', max_length=254),
        ),
    ]
