# Generated by Django 3.2.4 on 2021-08-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('whitenoise', 'Whitenoise'), ('sql', 'SQL'), ('javascript', 'JavaScript'), ('stripe', 'Stripe'), ('bootstrap5', 'Bootstrap5'), ('django', 'Django')], default='No Topic', max_length=254),
        ),
    ]
